# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=arm
CONFIG_USER_ONLY=yes
CONFIG_LINUX_USER=yes
TARGET_XML_FILES= /XenSource/MemoryMonitor/tools/ioemu-qemu-xen/gdb-xml/arm-core.xml /XenSource/MemoryMonitor/tools/ioemu-qemu-xen/gdb-xml/arm-vfp.xml /XenSource/MemoryMonitor/tools/ioemu-qemu-xen/gdb-xml/arm-vfp3.xml /XenSource/MemoryMonitor/tools/ioemu-qemu-xen/gdb-xml/arm-neon.xml
CONFIG_SOFTFLOAT=yes
TARGET_HAS_BFLT=yes
